plugins {
    id 'java'
}

repositories {
    mavenLocal()
    mavenCentral()
// TODO: uncomment to be able to fetch packages in your own repository
//    maven {
//        name = "GitHubPackages"
//        url = uri("https://maven.pkg.github.com/<your-username>/printscript")
//        credentials {
//            username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
//            password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
//        }
//    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    minHeapSize = "5m" // initial heap size
    maxHeapSize = "7m" // maximum heap size
}

dependencies {
    implementation 'org.example:com.ingsis.engine'
    implementation 'org.example:com.ingsis.common'
    implementation 'org.example:com.ingsis.charstream'
    implementation 'org.example:com.ingsis.lexer'
    implementation 'org.example:com.ingsis.syntactic'
    implementation 'org.example:com.ingsis.semantic'
    implementation 'org.example:com.ingsis.interpreter'
    implementation 'org.example:com.ingsis.formatter'
    implementation 'org.example:com.ingsis.sca'
    testImplementation 'junit:junit:4.13.1'
}

test {
    environment "BEST_FOOTBALL_CLUB", "San Lorenzo"
    useJUnit()
}
